# Generated by Django 2.2.2 on 2019-06-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coursdispenser',
            new_name='Emploi_temps',
        ),
    ]
