# Generated by Django 2.2.2 on 2019-06-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0003_auto_20190623_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi_temps',
            name='matiere',
        ),
        migrations.AddField(
            model_name='coursmardi',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Programme', verbose_name='Programme'),
        ),
        migrations.CreateModel(
            name='CoursVendredi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe')),
                ('matiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Matiere', verbose_name='Matière')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Programme', verbose_name='Programme')),
            ],
        ),
        migrations.CreateModel(
            name='CoursSamedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe')),
                ('matiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Matiere', verbose_name='Matière')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Programme', verbose_name='Programme')),
            ],
        ),
        migrations.CreateModel(
            name='CoursMercredi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe')),
                ('matiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Matiere', verbose_name='Matière')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Programme', verbose_name='Programme')),
            ],
        ),
        migrations.CreateModel(
            name='CoursLundi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe')),
                ('matiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Matiere', verbose_name='Matière')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Programme', verbose_name='Programme')),
            ],
        ),
        migrations.CreateModel(
            name='CoursJeudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe')),
                ('matiere', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Matiere', verbose_name='Matière')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Programme', verbose_name='Programme')),
            ],
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='coursjeudi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursJeudi', verbose_name='Cours Mardi'),
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='courslundi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursLundi', verbose_name='Cours Lundi'),
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='coursmercredi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursMercredi', verbose_name='Cours Mardi'),
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='courssamedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursSamedi', verbose_name='Cours Mardi'),
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='coursvendredi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursVendredi', verbose_name='Cours Mardi'),
        ),
    ]
