# Generated by Django 2.2.2 on 2019-06-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0004_auto_20190623_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursjeudi',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='coursmardi',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='coursmercredi',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='courssamedi',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='coursvendredi',
            name='programme',
        ),
        migrations.AlterField(
            model_name='emploi_temps',
            name='coursjeudi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursJeudi', verbose_name='Cours Jeudi'),
        ),
        migrations.AlterField(
            model_name='emploi_temps',
            name='coursmercredi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursMercredi', verbose_name='Cours Mercredi'),
        ),
        migrations.AlterField(
            model_name='emploi_temps',
            name='courssamedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursSamedi', verbose_name='Cours Samedi'),
        ),
        migrations.AlterField(
            model_name='emploi_temps',
            name='coursvendredi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.CoursVendredi', verbose_name='Cours Vendredi'),
        ),
    ]
