# Generated by Django 2.2.2 on 2019-06-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0005_auto_20190623_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='codeevaluation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code évaluation'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='periodeeval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Periodeeval', verbose_name='Période évaluation'),
        ),
        migrations.AlterField(
            model_name='programme_trans',
            name='heurdepart',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Heur de départ'),
        ),
        migrations.CreateModel(
            name='Evaluernote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(null=True, verbose_name='Note')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Eleve', verbose_name='Elève')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Evaluation', verbose_name='Evaluation')),
            ],
        ),
    ]
