# Generated by Django 2.2.2 on 2019-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0007_auto_20190709_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi_temps',
            name='codeemploi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code emploi temps'),
        ),
    ]
