# Generated by Django 2.2.2 on 2019-07-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0008_emploi_temps_codeemploi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi_temps',
            name='codeemploi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Code emploi temps'),
        ),
        migrations.CreateModel(
            name='Eleverecruter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeeleverecruter', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code élève recruté')),
                ('accepter', models.SmallIntegerField(default=0, verbose_name='Accepter')),
                ('datederecrute', models.CharField(max_length=30, verbose_name='Date de recrutement*')),
                ('dateConfirmerecrute', models.CharField(max_length=30, verbose_name='Date de la confirmation du recrutement*')),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Anneescolaire', verbose_name='Année scolaire* ')),
                ('elevecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Elevecon', verbose_name='Elève*')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Niveau', verbose_name='Niveau*')),
            ],
        ),
    ]
