# Generated by Django 2.2.2 on 2019-07-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0011_auto_20190718_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant_titulaire',
            name='anneescolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Anneescolaire', verbose_name='Année scolaire*'),
        ),
        migrations.AlterField(
            model_name='enseignant_titulaire',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', unique=True, verbose_name='Classe*'),
        ),
        migrations.AlterField(
            model_name='enseignant_titulaire',
            name='dateaffectation',
            field=models.CharField(max_length=30, null=True, verbose_name='Date affectation*'),
        ),
        migrations.AlterField(
            model_name='enseignant_titulaire',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Enseignant', unique=True, verbose_name='Enseignant*'),
        ),
        migrations.CreateModel(
            name='Certiicatsco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codecertificat', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code certificat')),
                ('anneescolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Anneescolaire', verbose_name='Année scolaire*')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Elève*')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Eleve', verbose_name='Elève*')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Etablissement', verbose_name='Etablissement* ')),
            ],
        ),
    ]
