# Generated by Django 2.2.2 on 2019-07-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0012_auto_20190724_0037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certiicatsco',
            new_name='Certificatsco',
        ),
    ]
