# Generated by Django 2.2.2 on 2019-07-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestschools', '0013_auto_20190724_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseildiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeconseildiscipline', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code Conseil')),
                ('libelleconseildisc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé conseil*')),
                ('dateconseil', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date de la tenue*')),
                ('libelledecision', models.CharField(max_length=230, verbose_name='Libellé décision*')),
                ('membreconseil', models.CharField(max_length=230, verbose_name='Membre(s) du conseil*')),
            ],
        ),
        migrations.CreateModel(
            name='Decisionconseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codedecision', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code décision')),
                ('libelledecision', models.CharField(max_length=100, verbose_name='Libellé décision*')),
            ],
        ),
        migrations.CreateModel(
            name='Statutenseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codestatut', models.CharField(max_length=60, null=True, verbose_name='Code statut')),
                ('libellestatutlng1', models.CharField(max_length=60, verbose_name='Libellé statut1*')),
                ('libellestatutlng2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Libellé statut2')),
            ],
        ),
        migrations.CreateModel(
            name='Type_contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codetype_contrat', models.CharField(max_length=60, null=True, verbose_name='Code type contrat')),
                ('libelletype_contrat', models.CharField(max_length=60, verbose_name='Libellé type contrat*')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matriculeens',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='date_naiss',
            field=models.CharField(max_length=100, verbose_name='Date de Naissance*'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='datedebut',
            field=models.CharField(max_length=60, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='datefin',
            field=models.CharField(max_length=60, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='certificatsco',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe*'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='dataentreefonctionpublique',
            field=models.CharField(max_length=30, null=True, verbose_name="Date d'entrée en fonction publique"),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='date_naiss',
            field=models.CharField(max_length=100, verbose_name='Date de Naissance*'),
        ),
        migrations.AlterField(
            model_name='enseignant_titulaire',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe*'),
        ),
        migrations.AlterField(
            model_name='enseignant_titulaire',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Enseignant', verbose_name='Enseignant*'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='libelleservicefinancier',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Libellé service financier'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='dateeval',
            field=models.CharField(max_length=20, verbose_name="Date de l'évaluation"),
        ),
        migrations.AlterField(
            model_name='periodeeval',
            name='datedebut',
            field=models.CharField(max_length=100, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='periodeeval',
            name='datefin',
            field=models.CharField(max_length=100, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_naiss',
            field=models.CharField(max_length=100, verbose_name='Date de Naissance*'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='datedebut',
            field=models.CharField(max_length=60, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='datefin',
            field=models.CharField(max_length=60, verbose_name='Date de fin'),
        ),
        migrations.CreateModel(
            name='Decisionfinalconseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codedecisionfinalconseil', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code décision final conseil')),
                ('libelledecisionfinalconseil', models.CharField(max_length=100, null=True, verbose_name='Libellé décision final conseil*')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Classe', verbose_name='Classe* ')),
                ('conseildiscipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Conseildiscipline', verbose_name='Conseil discipline* ')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Eleve', verbose_name='Nom complet élève* ')),
            ],
        ),
        migrations.AddField(
            model_name='conseildiscipline',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestschools.Sequence', verbose_name='Séquence* '),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='statutenseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Statutenseignant', verbose_name='Statut*'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='type_contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestschools.Type_contrat', verbose_name='Type de contrat*'),
        ),
    ]
